services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    

  backend:
    build:
      context: .
      dockerfile: ./devops/Dockerfile
    volumes:
      - .:/buddy
    ports:
      - "8000:8000"
    image: buddy:latest
    container_name: buddy_backend
    command: /server.sh
    env_file:
      - ./.env
    
    depends_on:
      - db

volumes:
  postgres_data: