# Generated by Django 4.2 on 2024-06-18 09:07

import core.utils.enums.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userpersonality'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('previous_session_gpa', models.DecimalField(decimal_places=4, default='0.00', max_digits=5)),
                ('expected_current_session_gpa', models.DecimalField(decimal_places=4, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.utils.enums.base.BaseModelBaseMixin, models.Model),
        ),
    ]
